// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Strings.sol";
import "@openzeppelin/contracts/utils/Base64.sol";

/// @title WhaleCards - Whalemon Trading Card Game
/// @author Built for the WHEL community on Tempo Network
/// @notice Mint unique Whalemon trading cards from your WHEL NFTs. 1 Whale = 1 Card, forever.
/// @dev Cards are free to mint (gas only in PATHUSD). Stats are committed by the oracle after AI generation.

interface IERC721Ownership {
    function ownerOf(uint256 tokenId) external view returns (address);
    function balanceOf(address owner) external view returns (uint256);
    function tokenOfOwnerByIndex(address owner, uint256 index) external view returns (uint256);
}

contract WhaleCards is ERC721, ERC721Enumerable, Ownable {
    using Strings for uint256;

    /* ========== CONSTANTS ========== */

    /// @notice The WHEL NFT contract on Tempo
    IERC721Ownership public immutable whaleNFT;

    /// @notice Maximum number of cards (matches WHEL supply)
    uint256 public constant MAX_CARDS = 3333;

    /* ========== STRUCTS ========== */

    /// @notice Card stats generated by AI from whale traits
    struct CardStats {
        uint16 attack;      // 1-100 base attack power
        uint16 defense;     // 1-100 base defense power
        uint16 health;      // 50-300 hit points
        uint16 speed;       // 1-100 determines turn order
        uint8 element;      // 0=Abyss, 1=Tide, 2=Storm, 3=Frost, 4=Coral, 5=Leviathan
        uint8 rarity;       // 0=Common, 1=Uncommon, 2=Rare, 3=Epic, 4=Legendary
        bytes32 abilityHash; // Hash of the ability name + description (full text stored off-chain)
        bool isSet;         // Whether stats have been committed by oracle
    }

    /* ========== STATE ========== */

    /// @notice Mapping from WHEL tokenId to whether a card has been minted
    mapping(uint256 => bool) public cardMinted;

    /// @notice Mapping from WHEL tokenId to card tokenId (they share the same ID)
    /// @dev Card tokenId == WHEL tokenId for simplicity
    mapping(uint256 => CardStats) public cardStats;

    /// @notice Address authorized to commit AI-generated stats
    address public oracle;

    /// @notice Base URI for card metadata
    string public baseMetadataURI;

    /// @notice Mapping from card tokenId to the original WHEL NFT image URI
    mapping(uint256 => string) public cardImageURI;

    /// @notice Element names for on-chain SVG rendering
    string[6] public elementNames = ["Abyss", "Tide", "Storm", "Frost", "Coral", "Leviathan"];

    /// @notice Rarity names
    string[5] public rarityNames = ["Common", "Uncommon", "Rare", "Epic", "Legendary"];

    /// @notice Element colors for card borders (hex without #)
    string[6] public elementColors = ["1a0a2e", "0ea5e9", "8b5cf6", "67e8f9", "f472b6", "dc2626"];

    /* ========== EVENTS ========== */

    event CardMinted(address indexed owner, uint256 indexed whaleId, uint256 indexed cardId);
    event StatsCommitted(uint256 indexed cardId, uint8 element, uint8 rarity);
    event OracleUpdated(address indexed oldOracle, address indexed newOracle);

    /* ========== ERRORS ========== */

    error NotWhaleOwner();
    error CardAlreadyMinted();
    error StatsAlreadySet();
    error OnlyOracle();
    error CardDoesNotExist();
    error InvalidStats();

    /* ========== CONSTRUCTOR ========== */

    /// @notice Deploy WhaleCards linked to the WHEL collection
    /// @param _whaleNFT Address of the WHEL NFT contract on Tempo
    /// @param _oracle Address authorized to commit AI-generated card stats
    constructor(
        address _whaleNFT,
        address _oracle
    ) ERC721("Whalemon", "WMON") Ownable(msg.sender) {
        whaleNFT = IERC721Ownership(_whaleNFT);
        oracle = _oracle;
    }

    /* ========== MINTING ========== */

    /// @notice Mint a Whalemon card from your WHEL NFT
    /// @param whaleId The token ID of the WHEL NFT you own
    /// @dev Free to mint - only costs gas (PATHUSD on Tempo)
    /// @dev Card ID will match the WHEL ID for easy reference
    function mintCard(uint256 whaleId) external {
        // Verify caller owns the whale
        if (whaleNFT.ownerOf(whaleId) != msg.sender) revert NotWhaleOwner();

        // Verify no card has been minted for this whale
        if (cardMinted[whaleId]) revert CardAlreadyMinted();

        // Mark as minted
        cardMinted[whaleId] = true;

        // Mint the card with same ID as the whale
        _safeMint(msg.sender, whaleId);

        emit CardMinted(msg.sender, whaleId, whaleId);
    }

    /// @notice Batch mint cards for multiple whales you own
    /// @param whaleIds Array of WHEL token IDs to mint cards for
    function batchMintCards(uint256[] calldata whaleIds) external {
        for (uint256 i = 0; i < whaleIds.length; i++) {
            uint256 whaleId = whaleIds[i];
            if (whaleNFT.ownerOf(whaleId) != msg.sender) revert NotWhaleOwner();
            if (cardMinted[whaleId]) revert CardAlreadyMinted();

            cardMinted[whaleId] = true;
            _safeMint(msg.sender, whaleId);

            emit CardMinted(msg.sender, whaleId, whaleId);
        }
    }

    /* ========== ORACLE / STATS ========== */

    /// @notice Commit AI-generated stats for a card (called by oracle after AI processing)
    /// @param cardId The card token ID to set stats for
    /// @param attack Attack power (1-100)
    /// @param defense Defense power (1-100)
    /// @param health Hit points (50-300)
    /// @param speed Speed stat (1-100)
    /// @param element Element type (0-5)
    /// @param rarity Rarity tier (0-4)
    /// @param abilityHash Hash of the ability data stored off-chain
    /// @param imageURI The original WHEL NFT image URL (IPFS/HTTP)
    function commitStats(
        uint256 cardId,
        uint16 attack,
        uint16 defense,
        uint16 health,
        uint16 speed,
        uint8 element,
        uint8 rarity,
        bytes32 abilityHash,
        string calldata imageURI
    ) external {
        if (msg.sender != oracle && msg.sender != owner()) revert OnlyOracle();
        if (!_exists(cardId)) revert CardDoesNotExist();
        if (cardStats[cardId].isSet) revert StatsAlreadySet();
        if (attack == 0 || attack > 100) revert InvalidStats();
        if (defense == 0 || defense > 100) revert InvalidStats();
        if (health < 50 || health > 300) revert InvalidStats();
        if (speed == 0 || speed > 100) revert InvalidStats();
        if (element > 5) revert InvalidStats();
        if (rarity > 4) revert InvalidStats();

        cardStats[cardId] = CardStats({
            attack: attack,
            defense: defense,
            health: health,
            speed: speed,
            element: element,
            rarity: rarity,
            abilityHash: abilityHash,
            isSet: true
        });

        // Store the original NFT image URI for on-chain SVG rendering
        if (bytes(imageURI).length > 0) {
            cardImageURI[cardId] = imageURI;
        }

        emit StatsCommitted(cardId, element, rarity);
    }

    /// @notice Batch commit stats for multiple cards
    function batchCommitStats(
        uint256[] calldata cardIds,
        uint16[] calldata attacks,
        uint16[] calldata defenses,
        uint16[] calldata healths,
        uint16[] calldata speeds,
        uint8[] calldata elements,
        uint8[] calldata rarities,
        bytes32[] calldata abilityHashes,
        string[] calldata imageURIs
    ) external {
        if (msg.sender != oracle && msg.sender != owner()) revert OnlyOracle();
        
        for (uint256 i = 0; i < cardIds.length; i++) {
            uint256 cardId = cardIds[i];
            if (!_exists(cardId)) revert CardDoesNotExist();
            if (cardStats[cardId].isSet) revert StatsAlreadySet();

            cardStats[cardId] = CardStats({
                attack: attacks[i],
                defense: defenses[i],
                health: healths[i],
                speed: speeds[i],
                element: elements[i],
                rarity: rarities[i],
                abilityHash: abilityHashes[i],
                isSet: true
            });

            if (bytes(imageURIs[i]).length > 0) {
                cardImageURI[cardId] = imageURIs[i];
            }

            emit StatsCommitted(cardId, elements[i], rarities[i]);
        }
    }

    /* ========== VIEWS ========== */

    /// @notice Get full card stats for a card
    function getCardStats(uint256 cardId) external view returns (CardStats memory) {
        if (!_exists(cardId)) revert CardDoesNotExist();
        return cardStats[cardId];
    }

    /// @notice Check if a whale has had its card minted
    function isCardMinted(uint256 whaleId) external view returns (bool) {
        return cardMinted[whaleId];
    }

    /// @notice Get all card IDs owned by an address
    function getCardsOf(address owner) external view returns (uint256[] memory) {
        uint256 count = balanceOf(owner);
        uint256[] memory cards = new uint256[](count);
        for (uint256 i = 0; i < count; i++) {
            cards[i] = tokenByIndex(i); // Note: use proper enumeration
        }
        return cards;
    }

    /// @notice Check if a token exists
    function _exists(uint256 tokenId) internal view returns (bool) {
        return _ownerOf(tokenId) != address(0);
    }

    /* ========== TOKEN URI (ON-CHAIN SVG) ========== */

    /// @notice Returns fully on-chain metadata with SVG card art
    function tokenURI(uint256 tokenId) public view override returns (string memory) {
        if (!_exists(tokenId)) revert CardDoesNotExist();

        CardStats memory stats = cardStats[tokenId];
        string memory cardName = string.concat("Whalemon #", tokenId.toString());

        if (!stats.isSet) {
            // Card minted but stats not yet committed - show loading state
            return string.concat(
                "data:application/json;base64,",
                Base64.encode(bytes(string.concat(
                    '{"name":"', cardName, '",',
                    '"description":"A Whalemon Trading Card awaiting its destiny. Stats will be revealed once the oracle processes this whale.",',
                    '"image":"data:image/svg+xml;base64,',
                    Base64.encode(bytes(_renderPendingCardSVG(tokenId))),
                    '"}'
                )))
            );
        }

        string memory elementName = elementNames[stats.element];
        string memory rarityName = rarityNames[stats.rarity];

        return string.concat(
            "data:application/json;base64,",
            Base64.encode(bytes(string.concat(
                '{"name":"', cardName, ' - ', elementName, ' ', rarityName, '",',
                '"description":"A ', rarityName, ' ', elementName, ' card from the Whalemon TCG. ATK:', 
                uint256(stats.attack).toString(), ' DEF:', uint256(stats.defense).toString(),
                ' HP:', uint256(stats.health).toString(), ' SPD:', uint256(stats.speed).toString(), '",',
                '"image":"data:image/svg+xml;base64,',
                Base64.encode(bytes(_renderCardSVG(tokenId, stats))),
                '",',
                '"attributes":[',
                    '{"trait_type":"Element","value":"', elementName, '"},',
                    '{"trait_type":"Rarity","value":"', rarityName, '"},',
                    '{"trait_type":"Attack","display_type":"number","value":', uint256(stats.attack).toString(), '},',
                    '{"trait_type":"Defense","display_type":"number","value":', uint256(stats.defense).toString(), '},',
                    '{"trait_type":"Health","display_type":"number","value":', uint256(stats.health).toString(), '},',
                    '{"trait_type":"Speed","display_type":"number","value":', uint256(stats.speed).toString(), '}',
                ']}'
            )))
        );
    }

    /// @dev Renders SVG for a card with stats
    function _renderCardSVG(uint256 tokenId, CardStats memory stats) internal view returns (string memory) {
        string memory borderColor = elementColors[stats.element];
        string memory elementName = elementNames[stats.element];
        string memory rarityName = rarityNames[stats.rarity];
        string memory imageTag;

        // Use actual NFT image if available, otherwise fallback to whale emoji
        if (bytes(cardImageURI[tokenId]).length > 0) {
            imageTag = string.concat(
                '<clipPath id="imgClip"><rect x="30" y="70" width="240" height="180" rx="10"/></clipPath>',
                '<image href="', cardImageURI[tokenId], '" x="30" y="70" width="240" height="180" clip-path="url(#imgClip)" preserveAspectRatio="xMidYMid slice"/>'
            );
        } else {
            imageTag = string.concat(
                '<circle cx="150" cy="160" r="70" fill="#', borderColor, '" opacity="0.15"/>',
                '<text x="150" y="170" text-anchor="middle" fill="#e2e8f0" font-size="48">&#x1F433;</text>'
            );
        }

        return string.concat(
            '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 300 420" style="font-family:monospace">',
            '<defs><linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">',
            '<stop offset="0%" stop-color="#0a0e27"/><stop offset="100%" stop-color="#0f172a"/>',
            '</linearGradient></defs>',
            '<rect width="300" height="420" rx="16" fill="url(#bg)"/>',
            '<rect x="4" y="4" width="292" height="412" rx="14" fill="none" stroke="#', borderColor, '" stroke-width="3" opacity="0.8"/>',
            '<text x="150" y="36" text-anchor="middle" fill="#e2e8f0" font-size="16" font-weight="bold">WHALE #', tokenId.toString(), '</text>',
            '<text x="150" y="56" text-anchor="middle" fill="#', borderColor, '" font-size="12">', elementName, ' | ', rarityName, '</text>',
            imageTag,
            '<line x1="30" y1="260" x2="270" y2="260" stroke="#', borderColor, '" opacity="0.4"/>',
            '<text x="40" y="290" fill="#94a3b8" font-size="11">ATK</text><text x="120" y="290" fill="#f87171" font-size="14" font-weight="bold">', uint256(stats.attack).toString(), '</text>',
            '<text x="170" y="290" fill="#94a3b8" font-size="11">DEF</text><text x="250" y="290" fill="#60a5fa" font-size="14" font-weight="bold">', uint256(stats.defense).toString(), '</text>',
            '<text x="40" y="320" fill="#94a3b8" font-size="11">HP</text><text x="120" y="320" fill="#4ade80" font-size="14" font-weight="bold">', uint256(stats.health).toString(), '</text>',
            '<text x="170" y="320" fill="#94a3b8" font-size="11">SPD</text><text x="250" y="320" fill="#facc15" font-size="14" font-weight="bold">', uint256(stats.speed).toString(), '</text>',
            '<rect x="20" y="350" width="260" height="50" rx="8" fill="#', borderColor, '" opacity="0.1"/>',
            '<text x="150" y="380" text-anchor="middle" fill="#', borderColor, '" font-size="11">WHALEMON TCG</text>',
            '</svg>'
        );
    }

    /// @dev Renders SVG for a card awaiting stats
    function _renderPendingCardSVG(uint256 tokenId) internal pure returns (string memory) {
        return string.concat(
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 420" style="font-family:monospace">',
            '<rect width="300" height="420" rx="16" fill="#0a0e27"/>',
            '<rect x="4" y="4" width="292" height="412" rx="14" fill="none" stroke="#334155" stroke-width="2" stroke-dasharray="8 4"/>',
            '<text x="150" y="36" text-anchor="middle" fill="#e2e8f0" font-size="16" font-weight="bold">WHALE #', tokenId.toString(), '</text>',
            '<text x="150" y="56" text-anchor="middle" fill="#64748b" font-size="12">Awaiting Destiny...</text>',
            '<text x="150" y="180" text-anchor="middle" fill="#475569" font-size="64">&#x1F433;</text>',
            '<text x="150" y="300" text-anchor="middle" fill="#475569" font-size="12">Stats generating...</text>',
            '<text x="150" y="380" text-anchor="middle" fill="#334155" font-size="11">WHALEMON TCG</text>',
            '</svg>'
        );
    }

    /* ========== ADMIN ========== */

    /// @notice Update the oracle address
    function setOracle(address _oracle) external onlyOwner {
        emit OracleUpdated(oracle, _oracle);
        oracle = _oracle;
    }

    /// @notice Update base metadata URI (for off-chain metadata fallback)
    function setBaseMetadataURI(string calldata _uri) external onlyOwner {
        baseMetadataURI = _uri;
    }

    /* ========== OVERRIDES ========== */

    function _update(address to, uint256 tokenId, address auth)
        internal override(ERC721, ERC721Enumerable) returns (address)
    {
        return super._update(to, tokenId, auth);
    }

    function _increaseBalance(address account, uint128 value)
        internal override(ERC721, ERC721Enumerable)
    {
        super._increaseBalance(account, value);
    }

    function supportsInterface(bytes4 interfaceId)
        public view override(ERC721, ERC721Enumerable) returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }
}
